[package]
name = "rds-wasm-demo"
version = "0.1.13"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
slint = "1.14"
wasm-bindgen = "0.2"
console_error_panic_hook = "0.1"

[build-dependencies]
slint-build = "1.14"
